# SPECIFY A BASE IMAGE
FROM node:alpine

# SPECIFY A WORKING DIRECTORY
WORKDIR /usr/app

# COPY package.json TO CONTAINER
COPY ./package.json ./

# INSTALL DEPENDENCIES
RUN npm install

# THEN COPY EVERYTHING ELSE
# SO CHANGES WILL NOT INVALID package.json CACHE
COPY ./ ./

# SET START COMMAND
CMD ["npm", "start"]