# SPECIFY A BASE IMAGE
FROM node:alpine

# SPECIFY A WORKING DIRECTORY
WORKDIR /usr/app

# COPY FILES TO CONTAINER
COPY ./ ./

# INSTALL DEPENDENCIES
RUN npm install

# SET START COMMAND
CMD ["npm", "start"]